### ISSUE TITLE
Singular interval_lengths

### ISSUE THREAD

**Issue by Sinetheta** [brendandeere/solidus_subscriptions#54]
If the interval lengths were singular then rails could help with humanizing the output.

```rb
'months'.pluralize(1) => 'months'
'month'.pluralize(2) => 'months'
```

**Comment by brendandeere** [comment]
@alexblackie Thoughts?

**Comment by alexblackie** [comment]
I have no opinion. If it makes things easier for someone then sure

**Comment by alexblackie** [comment]
This was completed in PR #65
